services:
  web:
    build: .
    container_name: price-compare
    ports:
      - "8000:8000" # Expose port 8000
    environment: # Environment variables
      DJANGO_SECRET_KEY: ${DJANGO_SECRET_KEY}
      DJANGO_DEBUG: ${DJANGO_DEBUG}
      DJANGO_ALLOWED_HOSTS: ${DJANGO_ALLOWED_HOSTS}
    volumes:
      - ./db.sqlite3:/app/db.sqlite3 # Persist database
      - static_data:/app/staticfiles
    env_file:
      - .env # Load environment variables from .env file
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80" # Expose port 80 for HTTP
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Nginx configuration file
      - static_data:/app/staticfiles # Serve static files
    restart: always
    depends_on:
      - web
volumes:
  static_data: # Named volume for static files
