# Generated by Django 5.2.2 on 2025-06-11 09:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='website',
            options={'ordering': ['name'], 'verbose_name': '購物網站', 'verbose_name_plural': '購物網站'},
        ),
        migrations.AddField(
            model_name='website',
            name='api_endpoint',
            field=models.URLField(default='https://google.com/search', help_text='網站搜尋API的端點URL'),
        ),
        migrations.AddField(
            model_name='website',
            name='api_key',
            field=models.CharField(blank=True, help_text='API金鑰(如果需要)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='website',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='website',
            name='headers',
            field=models.JSONField(blank=True, default=dict, help_text='請求標頭設定'),
        ),
        migrations.AddField(
            model_name='website',
            name='is_active',
            field=models.BooleanField(default=True, help_text='是否啟用此網站的搜尋功能'),
        ),
        migrations.AddField(
            model_name='website',
            name='max_results',
            field=models.IntegerField(default=50, help_text='單次搜尋最大結果數量'),
        ),
        migrations.AddField(
            model_name='website',
            name='search_delay',
            field=models.FloatField(default=1.0, help_text='搜尋間隔秒數，避免過於頻繁請求'),
        ),
        migrations.AddField(
            model_name='website',
            name='search_params',
            field=models.JSONField(blank=True, default=dict, help_text='搜尋參數設定'),
        ),
        migrations.AddField(
            model_name='website',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
