# Generated by Django 5.2.2 on 2025-06-12 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0002_alter_website_options_website_api_endpoint_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='website',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='website',
            name='api_endpoint',
        ),
        migrations.RemoveField(
            model_name='website',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='website',
            name='max_results',
        ),
        migrations.RemoveField(
            model_name='website',
            name='search_delay',
        ),
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.URLField(default='https://google.com/search', help_text='網站搜尋API的端點URL'),
        ),
    ]
