# Generated by Django 5.2.2 on 2025-06-12 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_app', '0003_alter_website_options_remove_website_api_endpoint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='api_endpoint',
            field=models.URLField(default='https://google.com/search', help_text='網站搜尋API的端點URL'),
        ),
        migrations.AlterField(
            model_name='website',
            name='url',
            field=models.URLField(unique=True),
        ),
    ]
